version: 2

seeds:
  - name: raw_customers
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: first_name
        description: "First name of the customer."
      - name: last_name
        description: "Last name of the customer."
    config:
      schema: seed_data

  - name: raw_orders
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Foreign key linking to customers."
        tests:
          - not_null
          - relationships:
              to: ref('raw_customers')
              field: id
      - name: order_date
        description: "Date when the order was placed."
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
    config:
      schema: seed_data

  - name: raw_payments
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Foreign key linking to orders."
        tests:
          - not_null
          - relationships:
              to: ref('raw_orders')
              field: id
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']
      - name: amount
        description: "Amount paid for the order."
        tests:
          - not_null
    config:
      schema: seed_data